---
- name: Configure sub-nginx for 3x-ui
  block:
    - import_tasks: certbot.yml

    - name: Find all 3x-ui config files
      find:
        paths: "{{ playbook_dir }}/../configs"
        patterns: "3x-ui_*.yml"
      register: config_files
      delegate_to: localhost

    - name: Extract suburls from config files
      no_log: true
      slurp:
        src: "{{ current_config_file.path }}"
      register: config_contents
      loop: "{{ config_files.files }}"
      loop_control:
        loop_var: current_config_file
      delegate_to: localhost

    - name: Set vpn_servers_sub variable
      set_fact:
        vpn_servers_sub: >-
          {%- set suburls = [] -%}
          {%- for content in config_contents.results -%}
            {%- if content.content is defined -%}
              {%- set config = content.content | b64decode | from_yaml -%}
              {%- if config.subscription is defined and config.subscription.suburl is defined -%}
                {%- set url = config.subscription.suburl -%}
                {%- set url_parts = url.split('/') -%}
                {%- set base_url = url_parts[:-1] | join('/') + '/' -%}
                {%- set _ = suburls.append(base_url) -%}
              {%- endif -%}
            {%- endif -%}
          {%- endfor -%}
          {{ suburls | join(' ') }}

    - import_tasks: filescopy.yml

    - name: Read .env file
      slurp:
        src: "{{ nginx_proxy_sub }}/.env"
      register: env_file

    - name: Parse .env file
      set_fact:
        env_vars: "{{ env_file.content | b64decode | regex_replace('^#.*$', '') | regex_replace('\n+', '\n') | regex_replace('^\n', '') | regex_replace('\n$', '') | regex_replace('=', ': ') | from_yaml }}"

    - name: Get inbound_sub_id from vpn_servers role
      set_fact:
        inbound_sub_id: "{{ hostvars[inventory_hostname]['inbound_sub_id'] }}"

    - name: Create all subs config file
      template:
        src: all_subs.yml.j2
        dest: "{{ playbook_dir }}/../configs/all_3x-ui_sub.yml"
        mode: "0644"
      delegate_to: localhost
  tags: [sub_nginx_3xui]
