---
- name: Include common file copy tasks
  include_tasks: "{{ playbook_dir }}/../roles/common/tasks/filescopy.yml"
  vars:
    restart_handler_name: "restart docker headscale"
    files_source_dir: "{{ role_path }}/files/"